# BenchFilter Training Configuration Settings

models:
  model1:
   name: meta-llama/Llama-3.2-3B-Instruct
   hflink: "https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct"
  model2:
    name: "Qwen/Qwen3-4B-Instruct-2507"
    hflink: "https://huggingface.co/Qwen/Qwen3-4B-Instruct-2507"
  model3:
    name: "tiiuae/Falcon3-3B-Instruct"
    hflink: "https://huggingface.co/tiiuae/Falcon3-3B-Instruct"


datasets:
  - name: "openai/gsm8k"
    link: "https://huggingface.co/datasets/openai/gsm8k"
    split: "train"
    description: "A dataset for evaluating mathematical problem-solving abilities."
  - name: "EleutherAI/hendrycks_math"
    link: "https://huggingface.co/datasets/EleutherAI/hendrycks_math"
    split: "train"
    description: "A dataset for assessing mathematical reasoning skills."

evaluation:
  output_dir: "./results"
  save_predictions: true
  
logging:
  level: "INFO"
  save_logs: true
  log_file: "./results/evaluation.log"
